/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FixedBottom: typeof import('./src/components/fixed-bottom/fixed-bottom.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/nav-bar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    PageConfigProvider: typeof import('./src/components/page-config-provider/page-config-provider.vue')['default']
    PageLoading: typeof import('./src/components/page-loading/page-loading.vue')['default']
    SafeArea: typeof import('./src/components/safe-area/safe-area.vue')['default']
    Tabs: typeof import('./src/components/tabs/tabs.vue')['default']
  }
}
